name: CLI Setup

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test_cli_linux_macos:
    runs-on: ${{ matrix.os }}
    env:
      QMK_HOME: ~/qmk_firmware
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run ci_tests
      run: ./ci_tests -a

  test_cli_win:
    runs-on: windows-latest
    env:
      QMK_HOME: $HOME/qmk_firmware

    steps:
    - uses: actions/checkout@v2.3.4

    - name: (MSYS2) Setup and install dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-python-pip

    - name: (MSYS2) Run ci_tests -a
      shell: msys2 {0}
      run: ./ci_tests -a
